# Generated by Django 5.0.4 on 2024-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ("-created_date",)},
        ),
        migrations.RenameField(
            model_name="news",
            old_name="publish",
            new_name="state",
        ),
        migrations.AddField(
            model_name="news",
            name="publish_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
