# Generated by Django 5.0.4 on 2024-05-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_options_rename_publish_news_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True),
        ),
    ]
