# Generated by Django 5.0.4 on 2024-05-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
